{"name": "test_Verify_error_displayed_when_invalid_username_entered[data2]", "status": "passed", "attachments": [{"name": "data was entered", "source": "c808e000-3212-4b48-98db-fbaec8e7636f-attachment.png", "type": "image/png"}, {"name": "Error Message is displayed", "source": "ed22ee51-35e4-4937-a273-72b67324e705-attachment.png", "type": "image/png"}], "parameters": [{"name": "data", "value": "['%@&*!']"}], "start": 1623561489657, "stop": 1623561500385, "uuid": "69e8533b-347a-43ec-ace7-8b685e5f90a5", "historyId": "e21aed30c34cc1a78d85dfb606e7895c", "testCaseId": "9771d5a1960ba0955ca6e6cfdc6c04ae", "fullName": "tests.test_login_adata_valid_and_invalid.Test_Login_Data#test_Verify_error_displayed_when_invalid_username_entered", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_adata_valid_and_invalid"}, {"name": "subSuite", "value": "Test_Login_Data"}, {"name": "host", "value": "HazelYu"}, {"name": "thread", "value": "9108-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_adata_valid_and_invalid"}]}