{"name": "test_Verify_error_displayed_when_invalid_username_entered[data2]", "status": "passed", "attachments": [{"name": "data was entered", "source": "be4a06fe-e052-48c0-a8dc-9233e5624702-attachment.png", "type": "image/png"}, {"name": "Error Message is displayed", "source": "b3c41d38-dcf5-4eb0-81c8-1677256b53c2-attachment.png", "type": "image/png"}], "parameters": [{"name": "data", "value": "['%@&*!']"}], "start": 1623560823716, "stop": 1623560828011, "uuid": "3571ea7e-1134-47b5-b653-d87bb831fdcd", "historyId": "e21aed30c34cc1a78d85dfb606e7895c", "testCaseId": "9771d5a1960ba0955ca6e6cfdc6c04ae", "fullName": "tests.test_login_adata_valid_and_invalid.Test_Login_Data#test_Verify_error_displayed_when_invalid_username_entered", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_adata_valid_and_invalid"}, {"name": "subSuite", "value": "Test_Login_Data"}, {"name": "host", "value": "HazelYu"}, {"name": "thread", "value": "9388-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_adata_valid_and_invalid"}]}