{"name": "test_Verify_error_displayed_when_invalid_username_entered[data0]", "status": "passed", "attachments": [{"name": "data was entered", "source": "9ce72d59-1756-473e-a9a7-1585c46381f7-attachment.png", "type": "image/png"}, {"name": "Error Message is displayed", "source": "281aa07c-0f30-4caf-91d2-89378dab36a9-attachment.png", "type": "image/png"}], "parameters": [{"name": "data", "value": "['notexist@mail.com']"}], "start": 1623562603360, "stop": 1623562614485, "uuid": "64c0c432-6ac7-430f-955e-aa6d32c0e7cc", "historyId": "a79a86d16a4d43e77cc7c62e2e1d8c05", "testCaseId": "9771d5a1960ba0955ca6e6cfdc6c04ae", "fullName": "tests.test_login_adata_valid_and_invalid.Test_Login_Data#test_Verify_error_displayed_when_invalid_username_entered", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_adata_valid_and_invalid"}, {"name": "subSuite", "value": "Test_Login_Data"}, {"name": "host", "value": "HazelYu"}, {"name": "thread", "value": "6236-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_adata_valid_and_invalid"}]}