{"name": "test_Verify_error_displayed_when_invalid_username_entered[data0]", "status": "passed", "attachments": [{"name": "data was entered", "source": "b42a3216-8354-409b-a135-4c8eb3e7c3b3-attachment.png", "type": "image/png"}, {"name": "Error Message is displayed", "source": "44039482-e89f-4ef1-a531-b2957c277096-attachment.png", "type": "image/png"}], "parameters": [{"name": "data", "value": "['notexist@mail.com']"}], "start": 1623560804033, "stop": 1623560815102, "uuid": "067bfa69-1ddb-47ca-a6d3-56000651ed34", "historyId": "a79a86d16a4d43e77cc7c62e2e1d8c05", "testCaseId": "9771d5a1960ba0955ca6e6cfdc6c04ae", "fullName": "tests.test_login_adata_valid_and_invalid.Test_Login_Data#test_Verify_error_displayed_when_invalid_username_entered", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_adata_valid_and_invalid"}, {"name": "subSuite", "value": "Test_Login_Data"}, {"name": "host", "value": "HazelYu"}, {"name": "thread", "value": "9388-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_adata_valid_and_invalid"}]}