{"name": "test_Verify_error_displayed_when_invalid_password_entered[data1]", "status": "passed", "attachments": [{"name": "data was entered", "source": "723836f0-0c4e-4fb5-9d1b-4b7eb06e57c6-attachment.png", "type": "image/png"}, {"name": "data was entered", "source": "99032faf-436d-4f7c-b17e-825f6ec872d8-attachment.png", "type": "image/png"}, {"name": "Error Message is displayed", "source": "91546372-7f4b-47ba-a618-7f8df3527ff3-attachment.png", "type": "image/png"}], "parameters": [{"name": "data", "value": "['+639654257082', 'isinvalid']"}], "start": 1623560868701, "stop": 1623560874822, "uuid": "24e72c09-7554-4f65-b9a7-293beefca6d7", "historyId": "a1031b2baab6db0cfafca88ce8d7739c", "testCaseId": "b6c8b3e51b072b623dd51f21e8815dd1", "fullName": "tests.test_login_adata_valid_and_invalid.Test_Login_Data#test_Verify_error_displayed_when_invalid_password_entered", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_adata_valid_and_invalid"}, {"name": "subSuite", "value": "Test_Login_Data"}, {"name": "host", "value": "HazelYu"}, {"name": "thread", "value": "9388-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_adata_valid_and_invalid"}]}