{"name": "test_Verify_error_displayed_when_invalid_password_entered[data1]", "status": "passed", "attachments": [{"name": "data was entered", "source": "adc22f1b-b146-4a67-b76b-91f8d9b906c6-attachment.png", "type": "image/png"}, {"name": "data was entered", "source": "58647d5c-d97e-4afe-8118-eab6be23b9ce-attachment.png", "type": "image/png"}, {"name": "Error Message is displayed", "source": "4a2b7786-586a-45d4-b889-3666bf2e3fea-attachment.png", "type": "image/png"}], "parameters": [{"name": "data", "value": "['+639654257082', 'isinvalid']"}], "start": 1623557223603, "stop": 1623557230074, "uuid": "b0062fa0-d060-41e3-a5de-c7827ecacd49", "historyId": "a1031b2baab6db0cfafca88ce8d7739c", "testCaseId": "b6c8b3e51b072b623dd51f21e8815dd1", "fullName": "tests.test_login_adata_valid_and_invalid.Test_Login_Data#test_Verify_error_displayed_when_invalid_password_entered", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_adata_valid_and_invalid"}, {"name": "subSuite", "value": "Test_Login_Data"}, {"name": "host", "value": "HazelYu"}, {"name": "thread", "value": "25292-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_adata_valid_and_invalid"}]}