{"name": "test_Verify_error_displayed_when_invalid_username_entered[data2]", "status": "passed", "attachments": [{"name": "data was entered", "source": "670606d4-b9ae-401b-bd95-9d465425e1ac-attachment.png", "type": "image/png"}, {"name": "Error Message is displayed", "source": "d2c891e0-f366-4814-8116-0c92547ae031-attachment.png", "type": "image/png"}], "parameters": [{"name": "data", "value": "['%@&*!']"}], "start": 1623557176161, "stop": 1623557184657, "uuid": "6f1c161c-b814-45c0-920b-90fc85e423c4", "historyId": "e21aed30c34cc1a78d85dfb606e7895c", "testCaseId": "9771d5a1960ba0955ca6e6cfdc6c04ae", "fullName": "tests.test_login_adata_valid_and_invalid.Test_Login_Data#test_Verify_error_displayed_when_invalid_username_entered", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_adata_valid_and_invalid"}, {"name": "subSuite", "value": "Test_Login_Data"}, {"name": "host", "value": "HazelYu"}, {"name": "thread", "value": "25292-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_adata_valid_and_invalid"}]}