{"name": "test_Verify_error_displayed_when_invalid_password_entered[data0]", "status": "passed", "attachments": [{"name": "data was entered", "source": "2d80bcf8-8329-46e5-83df-d837c5baa389-attachment.png", "type": "image/png"}, {"name": "data was entered", "source": "bc08215a-0e5e-474e-846e-3e192c01d89f-attachment.png", "type": "image/png"}, {"name": "Error Message is displayed", "source": "2eee989a-0c4f-4ae8-a6ae-22e7dc2a297f-attachment.png", "type": "image/png"}], "parameters": [{"name": "data", "value": "['mmhazel.yu@gmail.com', 'isinvalid']"}], "start": 1595949385982, "stop": 1595949397690, "uuid": "72d7e903-e6ed-4145-a85d-b8cf0b7e1d08", "historyId": "ccadd074f89991cdfb7fb393a4ae1469", "testCaseId": "b6c8b3e51b072b623dd51f21e8815dd1", "fullName": "tests.test_login_adata_valid_and_invalid.Test_Login_Data#test_Verify_error_displayed_when_invalid_password_entered", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_adata_valid_and_invalid"}, {"name": "subSuite", "value": "Test_Login_Data"}, {"name": "host", "value": "LAPTOP-45C52QUA"}, {"name": "thread", "value": "1476-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_adata_valid_and_invalid"}]}