{"name": "test_Verify_error_displayed_when_invalid_password_entered[data1]", "status": "passed", "attachments": [{"name": "data was entered", "source": "4a731ee5-26f4-4b69-984a-77e222fe25c7-attachment.png", "type": "image/png"}, {"name": "data was entered", "source": "d73924f8-8cb6-4abd-8a1d-b8b63c4202b2-attachment.png", "type": "image/png"}, {"name": "Error Message is displayed", "source": "2340a184-9718-4a66-82a2-ea09eff06f23-attachment.png", "type": "image/png"}], "parameters": [{"name": "data", "value": "['+639654257082', 'isinvalid']"}], "start": 1595949397712, "stop": 1595949409410, "uuid": "89c3d4f4-42df-4b14-b732-9c95b3a11d15", "historyId": "a1031b2baab6db0cfafca88ce8d7739c", "testCaseId": "b6c8b3e51b072b623dd51f21e8815dd1", "fullName": "tests.test_login_adata_valid_and_invalid.Test_Login_Data#test_Verify_error_displayed_when_invalid_password_entered", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_adata_valid_and_invalid"}, {"name": "subSuite", "value": "Test_Login_Data"}, {"name": "host", "value": "LAPTOP-45C52QUA"}, {"name": "thread", "value": "1476-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_adata_valid_and_invalid"}]}