{"name": "test_Verify_error_displayed_when_invalid_username_entered[data1]", "status": "passed", "attachments": [{"name": "data was entered", "source": "79be3e50-3a66-4522-a270-5cce8225ca13-attachment.png", "type": "image/png"}, {"name": "Error Message is displayed", "source": "1f60fbce-18df-4d4b-879e-8136605e1b8d-attachment.png", "type": "image/png"}], "parameters": [{"name": "data", "value": "['09654257082']"}], "start": 1623557168286, "stop": 1623557176156, "uuid": "d15df43f-9be5-43c7-9325-cb5e31edb589", "historyId": "96061be290c47b5b221f14a7d6d54183", "testCaseId": "9771d5a1960ba0955ca6e6cfdc6c04ae", "fullName": "tests.test_login_adata_valid_and_invalid.Test_Login_Data#test_Verify_error_displayed_when_invalid_username_entered", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_adata_valid_and_invalid"}, {"name": "subSuite", "value": "Test_Login_Data"}, {"name": "host", "value": "HazelYu"}, {"name": "thread", "value": "25292-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_adata_valid_and_invalid"}]}