{"name": "test_Verify_error_displayed_when_invalid_password_entered[data0]", "status": "passed", "attachments": [{"name": "data was entered", "source": "0e9ac27b-1c23-4924-b791-6e0c22b6465c-attachment.png", "type": "image/png"}, {"name": "data was entered", "source": "016034a1-5ebc-405c-b82e-cd272f205678-attachment.png", "type": "image/png"}, {"name": "Error Message is displayed", "source": "f2d76778-1d3d-469d-9a45-ad1956e32323-attachment.png", "type": "image/png"}], "parameters": [{"name": "data", "value": "['mmhazel.yu@gmail.com', 'isinvalid']"}], "start": 1623561527847, "stop": 1623561536896, "uuid": "33e66a42-000d-4ab7-829b-1230d745a2ab", "historyId": "ccadd074f89991cdfb7fb393a4ae1469", "testCaseId": "b6c8b3e51b072b623dd51f21e8815dd1", "fullName": "tests.test_login_adata_valid_and_invalid.Test_Login_Data#test_Verify_error_displayed_when_invalid_password_entered", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_adata_valid_and_invalid"}, {"name": "subSuite", "value": "Test_Login_Data"}, {"name": "host", "value": "HazelYu"}, {"name": "thread", "value": "9108-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_adata_valid_and_invalid"}]}