{"name": "test_Verify_error_displayed_when_invalid_username_entered[data1]", "status": "passed", "attachments": [{"name": "data was entered", "source": "3310f49f-3cbc-4bd8-9d7f-6d3875d3709c-attachment.png", "type": "image/png"}, {"name": "Error Message is displayed", "source": "7710367c-a2fd-4f46-b71c-155dcceaddb7-attachment.png", "type": "image/png"}], "parameters": [{"name": "data", "value": "['09654257082']"}], "start": 1623562614492, "stop": 1623562623074, "uuid": "5322882b-2894-41aa-9a1e-648d3dc0ee29", "historyId": "96061be290c47b5b221f14a7d6d54183", "testCaseId": "9771d5a1960ba0955ca6e6cfdc6c04ae", "fullName": "tests.test_login_adata_valid_and_invalid.Test_Login_Data#test_Verify_error_displayed_when_invalid_username_entered", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_adata_valid_and_invalid"}, {"name": "subSuite", "value": "Test_Login_Data"}, {"name": "host", "value": "HazelYu"}, {"name": "thread", "value": "6236-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_adata_valid_and_invalid"}]}