{"name": "test_Verify_error_displayed_when_invalid_password_entered[data0]", "status": "passed", "attachments": [{"name": "data was entered", "source": "f7ea3c74-f9cd-451a-bb57-fb543f4df163-attachment.png", "type": "image/png"}, {"name": "data was entered", "source": "99e7eb09-2c7d-43be-a14a-467583df73a6-attachment.png", "type": "image/png"}, {"name": "Error Message is displayed", "source": "85aae8eb-aec4-4704-8d84-a547379f910a-attachment.png", "type": "image/png"}], "parameters": [{"name": "data", "value": "['mmhazel.yu@gmail.com', 'isinvalid']"}], "start": 1623557212628, "stop": 1623557223597, "uuid": "78dd3d39-c671-418f-b8b4-5fe38215157e", "historyId": "ccadd074f89991cdfb7fb393a4ae1469", "testCaseId": "b6c8b3e51b072b623dd51f21e8815dd1", "fullName": "tests.test_login_adata_valid_and_invalid.Test_Login_Data#test_Verify_error_displayed_when_invalid_password_entered", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_adata_valid_and_invalid"}, {"name": "subSuite", "value": "Test_Login_Data"}, {"name": "host", "value": "HazelYu"}, {"name": "thread", "value": "25292-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_adata_valid_and_invalid"}]}