{"name": "test_Verify_error_displayed_when_invalid_password_entered[data0]", "status": "passed", "attachments": [{"name": "data was entered", "source": "efeb2976-f30f-49c2-b12e-6cfce7404044-attachment.png", "type": "image/png"}, {"name": "data was entered", "source": "c60b8bdb-0965-45c8-9ce3-1bdf6b156d7c-attachment.png", "type": "image/png"}, {"name": "Error Message is displayed", "source": "9ae9979a-b616-476f-8cb0-b577a1ac9c1b-attachment.png", "type": "image/png"}], "parameters": [{"name": "data", "value": "['mmhazel.yu@gmail.com', 'isinvalid']"}], "start": 1595949976853, "stop": 1595949992457, "uuid": "e4d6dca1-608b-4fed-984e-6fb1b81598e9", "historyId": "ccadd074f89991cdfb7fb393a4ae1469", "testCaseId": "b6c8b3e51b072b623dd51f21e8815dd1", "fullName": "tests.test_login_adata_valid_and_invalid.Test_Login_Data#test_Verify_error_displayed_when_invalid_password_entered", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_adata_valid_and_invalid"}, {"name": "subSuite", "value": "Test_Login_Data"}, {"name": "host", "value": "LAPTOP-45C52QUA"}, {"name": "thread", "value": "6008-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_adata_valid_and_invalid"}]}