{"name": "test_Verify_error_displayed_when_invalid_username_entered[data0]", "status": "passed", "attachments": [{"name": "data was entered", "source": "1e03d276-5dc0-4c51-8c9a-204b1a7f2c5f-attachment.png", "type": "image/png"}, {"name": "Error Message is displayed", "source": "777a1627-aff8-4478-a3fc-eaf710fb0f7c-attachment.png", "type": "image/png"}], "parameters": [{"name": "data", "value": "['notexist@mail.com']"}], "start": 1623561469844, "stop": 1623561480075, "uuid": "bf10ace0-7593-407b-8ede-f2a1eda79a8f", "historyId": "a79a86d16a4d43e77cc7c62e2e1d8c05", "testCaseId": "9771d5a1960ba0955ca6e6cfdc6c04ae", "fullName": "tests.test_login_adata_valid_and_invalid.Test_Login_Data#test_Verify_error_displayed_when_invalid_username_entered", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_adata_valid_and_invalid"}, {"name": "subSuite", "value": "Test_Login_Data"}, {"name": "host", "value": "HazelYu"}, {"name": "thread", "value": "9108-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_adata_valid_and_invalid"}]}