{"name": "test_Verify_error_displayed_when_invalid_password_entered[data1]", "status": "passed", "attachments": [{"name": "data was entered", "source": "d1c5eddc-54ea-41cd-a11e-b358b8a4313a-attachment.png", "type": "image/png"}, {"name": "data was entered", "source": "a791c88e-60a9-4af0-b47e-9d82d77a1d57-attachment.png", "type": "image/png"}, {"name": "Error Message is displayed", "source": "94db80a3-36b8-42e2-a955-428d6d603e11-attachment.png", "type": "image/png"}], "parameters": [{"name": "data", "value": "['+639654257082', 'isinvalid']"}], "start": 1595949992463, "stop": 1595950001228, "uuid": "7dfb650e-f283-423f-bb81-6edecd205dd7", "historyId": "a1031b2baab6db0cfafca88ce8d7739c", "testCaseId": "b6c8b3e51b072b623dd51f21e8815dd1", "fullName": "tests.test_login_adata_valid_and_invalid.Test_Login_Data#test_Verify_error_displayed_when_invalid_password_entered", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_adata_valid_and_invalid"}, {"name": "subSuite", "value": "Test_Login_Data"}, {"name": "host", "value": "LAPTOP-45C52QUA"}, {"name": "thread", "value": "6008-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_adata_valid_and_invalid"}]}